import { LiateDB, LiateCollection } from './LiateDB';
import { LiateError } from '../Liate_Security/LiateError';
import crypto from 'node:crypto';

/**
 * [40] - LiateCrud (Sovereign Schema-Driven Agentic CRUD & Entity Engine)
 * 
 * Automatically generates safe, typed AI agent tools (create, find, update, delete)
 * and LAPI HTTP REST endpoints from a single entity schema with field-level
 * guardrails, immutability checks, soft-deletes, and cryptographic audit trails.
 */

export interface CrudFieldDefinition {
  type: 'string' | 'number' | 'boolean' | 'object' | 'array' | 'date';
  required?: boolean;
  default?: any;
  enum?: (string | number)[];
  immutable?: boolean; // Cannot be modified after creation
  readOnly?: boolean;  // Generated by system, cannot be set by agent
  description?: string;
}

export type CrudSchema = Record<string, CrudFieldDefinition>;

export interface CrudOptions {
  schema: CrudSchema;
  db?: LiateDB;
  dbPath?: string;
  softDelete?: boolean; // Default: true
  trackAudit?: boolean; // Default: true
  primaryKey?: string;  // Default: 'id'
}

export interface CrudQueryOptions {
  where?: Record<string, any>;
  limit?: number;
  skip?: number;
  orderBy?: Record<string, 'asc' | 'desc'>;
}

export class LiateCrud<T extends Record<string, any> = Record<string, any>> {
  public entityName: string;
  public schema: CrudSchema;
  public options: Required<Omit<CrudOptions, 'db' | 'dbPath'>> & {
    db?: LiateDB;
    dbPath?: string;
  };
  private collection: LiateCollection;

  constructor(entityName: string, options: CrudOptions) {
    this.entityName = entityName.toLowerCase().trim();
    this.schema = options.schema || {};
    this.options = {
      schema: this.schema,
      db: options.db,
      dbPath: options.dbPath,
      softDelete: options.softDelete ?? true,
      trackAudit: options.trackAudit ?? true,
      primaryKey: options.primaryKey || 'id'
    };

    const dbInstance = options.db || new LiateDB({ path: options.dbPath || '.liate/data' });
    this.collection = dbInstance.collection(this.entityName);
  }

  /**
   * Validate and create a new record
   */
  public async create(data: Partial<T>, meta: Record<string, any> = {}): Promise<T> {
    const record: Record<string, any> = { ...data };
    const now = Date.now();

    // Generate Primary Key if absent
    const pk = this.options.primaryKey;
    if (!record[pk]) {
      record[pk] = `${this.entityName}_${crypto.randomBytes(6).toString('hex')}`;
    }

    // Apply defaults and validate schema
    for (const [field, def] of Object.entries(this.schema)) {
      if (def.readOnly && record[field] !== undefined) {
        delete record[field]; // Strip read-only fields
      }
      if (record[field] === undefined && def.default !== undefined) {
        record[field] = typeof def.default === 'function' ? def.default() : def.default;
      }
      if (def.required && (record[field] === undefined || record[field] === null)) {
        throw new LiateError('INVALID_JSON_OUTPUT', `Missing required field: '${field}' for ${this.entityName}`);
      }
      if (def.enum && record[field] !== undefined && !def.enum.includes(record[field])) {
        throw new LiateError('INVALID_JSON_OUTPUT', `Invalid value for '${field}'. Allowed values: ${def.enum.join(', ')}`);
      }
    }

    // Audit metadata
    if (this.options.trackAudit) {
      record.createdAt = now;
      record.updatedAt = now;
      record.createdBy = meta.agentName || meta.userId || 'system';
    }

    if (this.options.softDelete) {
      record.isDeleted = false;
    }

    await this.collection.insert(record as any);
    return record as T;
  }

  /**
   * Find record by primary key ID
   */
  public async findById(id: string): Promise<T | null> {
    const pk = this.options.primaryKey;
    const filter: Record<string, any> = { [pk]: id };
    if (this.options.softDelete) {
      filter.isDeleted = false;
    }

    const records = await this.collection.find(filter);
    return (records[0] as T) || null;
  }

  /**
   * Query records with filtering, pagination, and sorting
   */
  public async find(options: CrudQueryOptions = {}): Promise<T[]> {
    const filter: Record<string, any> = { ...(options.where || {}) };
    if (this.options.softDelete && filter.isDeleted === undefined) {
      filter.isDeleted = false;
    }

    const records = await this.collection.find(filter, {
      limit: options.limit || 50,
      offset: options.skip || 0
    });

    return records as T[];
  }

  /**
   * Update an existing record with immutable field protection
   */
  public async update(id: string, patch: Partial<T>, meta: Record<string, any> = {}): Promise<T | null> {
    const existing = await this.findById(id);
    if (!existing) {
      return null;
    }

    const cleanPatch: Record<string, any> = { ...patch };

    // Prevent altering Primary Key or Immutable fields
    const pk = this.options.primaryKey;
    delete cleanPatch[pk];

    for (const [field, def] of Object.entries(this.schema)) {
      if (def.immutable && cleanPatch[field] !== undefined) {
        throw new LiateError('GUARDRAIL_BLOCKED', `Field '${field}' is immutable and cannot be updated`);
      }
      if (def.readOnly) {
        delete cleanPatch[field];
      }
      if (def.enum && cleanPatch[field] !== undefined && !def.enum.includes(cleanPatch[field])) {
        throw new LiateError('INVALID_JSON_OUTPUT', `Invalid value for '${field}'. Allowed values: ${def.enum.join(', ')}`);
      }
    }

    if (this.options.trackAudit) {
      cleanPatch.updatedAt = Date.now();
      cleanPatch.updatedBy = meta.agentName || meta.userId || 'system';
    }

    await this.collection.update({ [pk]: id }, cleanPatch);
    return await this.findById(id);
  }


  /**
   * Delete record (soft-delete by default or hard-delete)
   */
  public async delete(id: string, meta: Record<string, any> = {}): Promise<boolean> {
    const existing = await this.findById(id);
    if (!existing) {
      return false;
    }

    const pk = this.options.primaryKey;

    if (this.options.softDelete) {
      await this.collection.update(
        { [pk]: id },
        {
          isDeleted: true,
          deletedAt: Date.now(),
          deletedBy: meta.agentName || meta.userId || 'system'
        }
      );
      return true;
    }

    const deleted = await this.collection.delete({ [pk]: id });
    return deleted > 0;
  }

  /**
   * Count active records matching filter
   */
  public async count(where: Record<string, any> = {}): Promise<number> {
    const filter = { ...where };
    if (this.options.softDelete && filter.isDeleted === undefined) {
      filter.isDeleted = false;
    }
    const list = await this.collection.find(filter);
    return list.length;
  }

  /**
   * Convert entire CRUD entity into auto-generated Agent Tools for LiateAgent.tools
   */
  public toTools(): any[] {
    const entity = this.entityName;
    const pk = this.options.primaryKey;

    // Build parameter schema for creation
    const createProperties: Record<string, any> = {};
    const requiredFields: string[] = [];

    for (const [key, def] of Object.entries(this.schema)) {
      if (!def.readOnly) {
        createProperties[key] = {
          type: def.type === 'date' ? 'string' : def.type,
          description: def.description || `The ${key} value`
        };
        if (def.enum) {
          createProperties[key].enum = def.enum;
        }
        if (def.required) {
          requiredFields.push(key);
        }
      }
    }

    return [
      {
        name: `create_${entity}`,
        description: `Creates a new ${entity} record in the sovereign database`,
        parameters: {
          type: 'object',
          properties: createProperties,
          required: requiredFields
        },
        execute: async (args: any) => this.create(args)
      },
      {
        name: `get_${entity}`,
        description: `Retrieves a specific ${entity} by its unique ${pk}`,
        parameters: {
          type: 'object',
          properties: {
            [pk]: { type: 'string', description: `Unique ID (${pk}) of the ${entity}` }
          },
          required: [pk]
        },
        execute: async (args: any) => this.findById(args[pk])
      },
      {
        name: `list_${entity}`,
        description: `Queries and lists ${entity} records with optional filtering`,
        parameters: {
          type: 'object',
          properties: {
            filter: { type: 'object', description: 'Filter conditions (key-value pairs)' },
            limit: { type: 'number', description: 'Max number of records to return' }
          }
        },
        execute: async (args: any) => this.find({ where: args.filter, limit: args.limit })
      },
      {
        name: `update_${entity}`,
        description: `Updates an existing ${entity} record by its ${pk}`,
        parameters: {
          type: 'object',
          properties: {
            [pk]: { type: 'string', description: `Unique ID (${pk}) of the ${entity}` },
            patch: { type: 'object', description: 'Key-value fields to update' }
          },
          required: [pk, 'patch']
        },
        execute: async (args: any) => this.update(args[pk], args.patch)
      },
      {
        name: `delete_${entity}`,
        description: `Safely deletes a ${entity} record by its ${pk}`,
        parameters: {
          type: 'object',
          properties: {
            [pk]: { type: 'string', description: `Unique ID (${pk}) of the ${entity} to delete` }
          },
          required: [pk]
        },
        execute: async (args: any) => this.delete(args[pk])
      }
    ];
  }
}

export const Crud = LiateCrud;
